<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */

/**
 * Autoload composer packages & bootstrap WordPress settings from ../config/
 */
require_once(__DIR__ . '/vendor/autoload.php');
require_once(__DIR__ . '/config/wp-config.php');


/*
 * Pro tip: Don't ever edit below that fucking line:
 * https://github.com/wp-cli/wp-cli/issues/1631
 */

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
    define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
